title: [Giri kumar]
description: [Where Innovation Meets Data Science]
show_downloads: ["true" ]
logo:[ https://github.com/giri2021/giri-kumar/blob/main/web%20image/my%20photo.png]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
